#create kuberenets manifest deployment for argo cd , for visa-service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-service-deployment
  namespace: VisaWheels
  labels:
    app: VisaWheels
    service: main-service
spec:
replicas: 2
selector:
  matchLabels:
    app: VisaWheels
    service: main-service
template:
  metadata:
    labels:
      app: VisaWheels
      service: main-service
  spec:
  containers:
  - name: main-service
    image: talyahalomy/main-service:latest
    ports: 9001