apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deployment
  namespace: visawheels
  labels:
    app: visawheels
spec:
  replicas: 2
  selector:
    matchLabels:
      app: visawheels
  template:
    metadata:
      labels:
        app: visawheels
    spec:
      containers:
      - name: main-service
        image: talyahalomy/main-service:latest
        ports:
        - containerPort: 9001

