apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deployment
  namespace: visawheels
  labels:
    app: visawheels
spec:
  replicas: 2
  selector:
    matchLabels:
      app: visawheels
      service: main-service
  template:
    metadata:
      labels:
        app: visawheels
    spec:
      containers:
       - name: main-service
         image: talyahalomy/main-service:latest
         env:
           - name: TARGET_URL
             valueFrom:
                configMapKeyRef:
                name: main-config-map
                key: TARGET_URL
    ports:
    - containerPort: 9001

