apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-deployment
  namespace: visawheels
  labels:
    app: visawheels
spec:
  replicas: 3
  selector:
    matchLabels:
      app: visawheels
  template:
    metadata:
      labels:
        app: visawheels
    spec:
      containers:
       - name: visa-service
         image: talyahalomy/visa-service:latest
         ports:
         - containerPort: 9010    
       -  name: main-service
          image: talyahalomy/main-config-map:latest
          ports:
          - containerPort: 9011
          envFrom:
          - configMapRef:
              name: main-config-map
      

