

apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-service-deployment
  namespace: visawheels
  labels:
    app: visasheels
    service: main-service
spec:
replicas: 2
selector:
  matchLabels:
    app: visasheels
    service: main-service
template:
  metadata:
    labels:
      app: visasheels
      service: main-service
  spec:
  containers:
  - name: main-service
    image: talyahalomy/main-service:latest
    ports: 9001

