
apiVersion: apps/v1
kind: Service
metadata:
  name: visa-service
  namespace: visawheels
  labels:
    app: visasheels
    service: visa-service
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP       
